version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: develop
    container_name: snsc_app
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:16.2
    container_name: snsc_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo

volumes:
  postgres_data:
