# Generated by Django 5.0.4 on 2024-04-14 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='サイトID')),
                ('site_name', models.CharField(max_length=50, verbose_name='サイト名')),
                ('is_active', models.BooleanField(default=False, verbose_name='アクティブなサイトか否か')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
            options={
                'db_table': 'site',
            },
        ),
    ]
