# Generated by Django 5.0.4 on 2024-04-21 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='SNS識別子')),
                ('name', models.CharField(max_length=50, verbose_name='SNS名')),
                ('is_active', models.BooleanField(default=False, verbose_name='使用フラグ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'SNSマスタ',
                'verbose_name_plural': 'SNSマスタ',
                'db_table': 'sns',
            },
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='サイト識別子'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='使用フラグ'),
        ),
    ]
