# Generated by Django 5.0.4 on 2024-04-28 04:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sns_rename_site_name_site_name_alter_site_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='投稿識別子')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='投稿タイトル')),
                ('like_count', models.IntegerField(blank=True, null=True, verbose_name='投稿いいね数')),
                ('comments_count', models.IntegerField(blank=True, null=True, verbose_name='投稿コメント数')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='投稿詳細文')),
                ('permalink', models.URLField(max_length=500, verbose_name='投稿リンク')),
                ('posted_at', models.DateTimeField(verbose_name='投稿日')),
                ('is_active', models.BooleanField(default=False, verbose_name='使用フラグ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='web.site')),
                ('sns', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='web.sns')),
            ],
            options={
                'verbose_name': '投稿マスタ',
                'verbose_name_plural': '投稿マスタ',
                'db_table': 'post',
            },
        ),
    ]
