# Generated by Django 5.0.4 on 2024-04-14 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'サイトマスタ', 'verbose_name_plural': 'サイトマスタ'},
        ),
        migrations.CreateModel(
            name='SiteOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site')),
                ('snsc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'サイト所有権紐付けテーブル',
                'verbose_name_plural': 'サイト所有権紐付けテーブル',
                'db_table': 'site_ownership',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='snsc_users',
            field=models.ManyToManyField(through='web.SiteOwnership', to=settings.AUTH_USER_MODEL),
        ),
    ]
