# Generated by Django 5.0.4 on 2024-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_post_username_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=50, verbose_name='投稿ユーザーネーム'),
        ),
    ]
