# Generated by Django 5.0.4 on 2024-04-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.site'),
        ),
        migrations.AddField(
            model_name='sns',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SNS情報取得トークン'),
        ),
    ]
