# Generated by Django 5.0.4 on 2024-04-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sns_site_sns_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site'),
        ),
    ]
