# Generated by Django 5.0.4 on 2024-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_sns_name_sns_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SNS情報取得識別子'),
        ),
        migrations.AddField(
            model_name='sns',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SNSユーザーネーム'),
        ),
        migrations.AddField(
            model_name='sns',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SNS情報取得バージョン'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='type',
            field=models.CharField(choices=[('IG', 'Instagram'), ('TK', 'TikTok')], max_length=10, verbose_name='SNS種別'),
        ),
    ]
