# Generated by Django 5.0.4 on 2024-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_sns_api_id_sns_username_sns_version_alter_sns_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sns',
            name='api_id',
        ),
        migrations.AddField(
            model_name='sns',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SNS情報取得アカウント識別子'),
        ),
        migrations.AddField(
            model_name='sns',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='SNSユーザー説明文'),
        ),
        migrations.AddField(
            model_name='sns',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='SNSフォロワー数'),
        ),
        migrations.AddField(
            model_name='sns',
            name='follows_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='SNSフォロー数'),
        ),
        migrations.AddField(
            model_name='sns',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SNSユーザー名(日本語対応)'),
        ),
        migrations.AddField(
            model_name='sns',
            name='post_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='SNS投稿数'),
        ),
        migrations.AddField(
            model_name='sns',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='SNSプロフィール画像URL'),
        ),
        migrations.AddField(
            model_name='sns',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='SNSユーザーウェブサイト'),
        ),
    ]
