# Generated by Django 5.0.4 on 2024-04-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_sns_options_remove_sns_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsuseraccount',
            name='sns',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.sns'),
        ),
    ]
