# Generated by Django 5.0.4 on 2024-04-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_snsuseraccount_sns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snsuseraccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='snsuseraccount',
            name='sns',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.sns'),
        ),
        migrations.AlterField(
            model_name='snsuseraccount',
            name='username',
            field=models.CharField(max_length=50, verbose_name='SNSユーザーネーム'),
        ),
    ]
