# Generated by Django 5.0.4 on 2024-04-29 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_snsuseraccount_id_alter_snsuseraccount_sns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sns',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='token',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='version',
        ),
        migrations.RemoveField(
            model_name='snsuseraccount',
            name='username',
        ),
        migrations.AddField(
            model_name='sns',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='各SNSユーザーアカウントにおける識別子'),
        ),
        migrations.CreateModel(
            name='SnsApiAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='SNS情報取得アカウント識別子')),
                ('api_account_id', models.CharField(max_length=50, verbose_name='各SNSにおける情報取得アカウント識別子')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='SNS情報取得バージョン')),
                ('token', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SNS情報取得トークン')),
                ('is_active', models.BooleanField(default=False, verbose_name='使用フラグ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('sns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sns')),
            ],
            options={
                'verbose_name': 'SNS情報取得アカウントマスタ',
                'verbose_name_plural': 'SNS情報取得アカウントマスタ',
                'db_table': 'sns_api_account',
            },
        ),
    ]
