# Generated by Django 5.0.4 on 2024-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_sns_account_id_remove_sns_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='username',
            field=models.CharField(max_length=50, verbose_name='各SNSユーザーアカウントにおける識別子'),
        ),
    ]
