# Generated by Django 5.0.4 on 2024-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_sns_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsapiaccount',
            name='api_account_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='各SNSにおける情報取得アカウント識別子'),
        ),
    ]
