# Generated by Django 5.0.4 on 2024-04-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_snsapiaccount_api_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteownership',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='使用フラグ'),
        ),
    ]
