# Generated by Django 5.0.4 on 2024-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_siteownership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='siteownership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='siteownership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='snsapiaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='snsapiaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='snsuseraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='snsuseraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
