# Generated by Django 5.0.4 on 2024-05-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_post_created_at_alter_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='site',
        ),
        migrations.AddField(
            model_name='post',
            name='sns_post_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='各SNSにおける投稿識別子'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.sns'),
        ),
    ]
