# Generated by Django 5.0.4 on 2024-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_post_site_post_sns_post_id_alter_post_sns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sns_post_id',
            field=models.CharField(max_length=50, verbose_name='各SNSにおける投稿識別子'),
        ),
    ]
