# Generated by Django 5.0.4 on 2024-05-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_post_sns_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
