# Generated by Django 5.0.4 on 2024-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_post_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snscuser',
            options={'verbose_name': 'SNSCユーザーマスタ', 'verbose_name_plural': 'SNSCユーザーマスタ'},
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='サイト名'),
        ),
    ]
