# Generated by Django 5.0.4 on 2024-05-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_snsuseraccount_options_postmedia_list_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'list_order'), name='uq_post_media_list_order'),
        ),
    ]
