# Generated by Django 5.0.4 on 2024-06-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProduct',
            fields=[
                ('is_active', models.BooleanField(default=False, verbose_name='使用フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='投稿関連商品識別子')),
                ('name', models.CharField(max_length=100, verbose_name='投稿関連商品名')),
                ('page_url', models.URLField(max_length=1000, verbose_name='投稿関連商品ページのURL')),
                ('image_url', models.URLField(max_length=1000, verbose_name='投稿関連商品画像のURL')),
                ('list_order', models.PositiveSmallIntegerField(default=0, verbose_name='一覧表示する際の優先度')),
            ],
            options={
                'verbose_name': '投稿関連商品',
                'verbose_name_plural': '投稿関連商品',
                'db_table': 'post_product',
            },
        ),
        migrations.CreateModel(
            name='PostProductRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='使用フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.post')),
                ('post_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.postproduct')),
            ],
            options={
                'verbose_name': '投稿関連商品紐付けテーブル',
                'verbose_name_plural': '投稿関連商品紐付けテーブル',
                'db_table': 'post_product_relationship',
            },
        ),
        migrations.AddField(
            model_name='postproduct',
            name='posts',
            field=models.ManyToManyField(through='web.PostProductRelationship', to='web.post'),
        ),
    ]
