# Generated by Django 5.0.4 on 2024-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_postproduct_options_alter_post_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='list_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='一覧表示する際の優先度'),
        ),
        migrations.AlterField(
            model_name='postproduct',
            name='list_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='一覧表示する際の優先度'),
        ),
    ]
