# Generated by Django 5.0.4 on 2024-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_remove_postmedia_uq_post_media_list_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, default='', verbose_name='投稿詳細文'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='投稿コメント数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='投稿いいね数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='投稿タイトル'),
            preserve_default=False,
        ),
    ]
